### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by michaelmattig** [jdroenner/geo-processing-incubator#1]
The configuration of the app shouldn't be done in the code (e.g. base_path).

I'd like to volunteer implementing the loading of the configuration from a config file.

My question: should we just use a JSON file for configuration (we need JSON parsing capabilities anyway) or use a more sophisticated create like https://github.com/mehcode/config-rs ?

**Comment by jdroenner** [comment]
I guess config-rs is the right crate for this :)

**Comment by michaelmattig** [comment]
Solved with https://github.com/jdroenner/geo-processing-incubator/pull/2
